apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: vsphereplans.pks.vcna.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.description
    name: Description
    type: string
  group: pks.vcna.io
  names:
    kind: VSpherePlan
    plural: vsphereplans
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            compute:
              description: ComputeSpec is a vSphere Compute specification.
              properties:
                masters:
                  description: MastersSpec is the vSphere Compute Masters specification.
                  properties:
                    memoryMb:
                      description: MemoryMB is the amount of memory in Mb to be assigned
                        to each master VM.
                      format: int64
                      minimum: 2
                      type: integer
                    numCpus:
                      description: NumCPUs is the number of CPUs to be assigned to
                        each master VM.
                      format: int32
                      minimum: 1
                      type: integer
                    replicas:
                      description: Replicas is the number of master VMs.
                      format: int32
                      minimum: 1
                      type: integer
                    vmFolder:
                      description: VMFolder is the vCenter folder where master VMs
                        will be located.
                      type: string
                    zones:
                      description: Zones are the zones where master VMs will be located.
                      items:
                        properties:
                          cluster:
                            description: Cluster is the name of the vCenter cluster
                              associated with the Zone.
                            type: string
                          datacenter:
                            description: Datacenter is the name of the vCenter datacenter
                              associated with the Zone.
                            type: string
                          name:
                            description: Name is the name of the Zone.
                            type: string
                          resourcePool:
                            description: ResourcePool is the name of the vCenter resource
                              pool associated with the Zone.
                            type: string
                        required:
                        - name
                        - datacenter
                        - cluster
                        type: object
                      minItems: 1
                      type: array
                  required:
                  - replicas
                  - numCpus
                  - memoryMb
                  - vmFolder
                  - zones
                  type: object
                workers:
                  description: WorkersSpec is the vSphere Compute Workers specification.
                  properties:
                    memoryMb:
                      description: MemoryMB is the amount of memory in Mb to be assigned
                        to each worker VM.
                      format: int64
                      minimum: 2
                      type: integer
                    numCpus:
                      description: NumCPUs is the number of CPUs to be assigned to
                        each worker VM.
                      format: int32
                      minimum: 1
                      type: integer
                    replicas:
                      description: Replicas is the number of worker VMs.
                      format: int32
                      minimum: 0
                      type: integer
                    vmFolder:
                      description: VMFolder is the vCenter folder where master VMs
                        will be located.
                      type: string
                    zones:
                      description: Zones are the zones where worker VMs will be located.
                      items:
                        properties:
                          cluster:
                            description: Cluster is the name of the vCenter cluster
                              associated with the Zone.
                            type: string
                          datacenter:
                            description: Datacenter is the name of the vCenter datacenter
                              associated with the Zone.
                            type: string
                          name:
                            description: Name is the name of the Zone.
                            type: string
                          resourcePool:
                            description: ResourcePool is the name of the vCenter resource
                              pool associated with the Zone.
                            type: string
                        required:
                        - name
                        - datacenter
                        - cluster
                        type: object
                      minItems: 1
                      type: array
                  required:
                  - replicas
                  - numCpus
                  - memoryMb
                  - vmFolder
                  - zones
                  type: object
              required:
              - masters
              - workers
              type: object
            description:
              description: Description is the description of the vSphere Plan.
              type: string
            network:
              description: NetworkSpec is a vSphere Network specification.
              properties:
                dns:
                  description: DNS is a list of Domain Name Servers.
                  items:
                    type: string
                  minItems: 1
                  type: array
                dvs:
                  description: DVSNetworkSpec is the vSphere DVS Network specification.
                  properties:
                    name:
                      description: Name is the name of the vSphere Network.
                      type: string
                  required:
                  - name
                  type: object
                nsxt:
                  description: NSXTNetworkSpec is the vSphere NSX-T Network specification.
                  properties:
                    credentialsSecretRef:
                      description: Secret containing vSphere credentials.
                      type: object
                    floatingIPPoolIds:
                      description: FloatingIPPoolIDs are the IDs of the Floating IP
                        Pools used to create VMs.
                      items:
                        type: string
                      minItems: 1
                      type: array
                    insecure:
                      description: Insecure determines whether communication with
                        NSX-T manager uses SSL validation.
                      type: boolean
                    ipBlockIds:
                      description: IPBlockID is the ID of the IP Block used to create
                        VMs.
                      items:
                        type: string
                      minItems: 1
                      type: array
                    lbSize:
                      description: LBSize is size of the Load Balancer.
                      type: string
                    natMode:
                      description: NatMode indicates if NAT should be used.
                      type: boolean
                    podSubnetPrefix:
                      description: PodSubnetPrefix is prefix of the POD subnet.
                      format: int64
                      type: integer
                  required:
                  - credentialsSecretRef
                  - insecure
                  - ipBlockIds
                  - floatingIPPoolIds
                  - natMode
                  - lbSize
                  type: object
              type: object
            provider:
              description: ProviderSpec is the vSphere Provider specification.
              properties:
                credentialsSecretRef:
                  description: Secret containing vSphere credentials.
                  type: object
                insecure:
                  description: Insecure determines whether communication with vCenter
                    uses SSL validation.
                  type: boolean
              required:
              - credentialsSecretRef
              - insecure
              type: object
            storage:
              description: StorageSpec is a vSphere Storage specification.
              properties:
                masters:
                  description: MastersSpec is the vSphere Storage Masters specification.
                  properties:
                    datastore:
                      description: Datastore is the name of the datastore to be used
                        by the Worker VMs.
                      type: string
                    disks:
                      description: Disks are the disks to be attached to the master
                        VMs.
                      items:
                        properties:
                          label:
                            description: Label is the label of the Disk.
                            type: string
                          sizeGb:
                            description: SizeGb is the size in Gb of the disk.
                            format: int64
                            minimum: 1
                            type: integer
                        required:
                        - sizeGb
                        type: object
                      minItems: 1
                      type: array
                  required:
                  - datastore
                  - disks
                  type: object
                workers:
                  description: WorkersSpec is the vSphere Storage Workers specification.
                  properties:
                    datastore:
                      description: Datastore is the name of the datastore to be used
                        by the Worker VMs.
                      type: string
                    disks:
                      description: Disks are the disks to be attached to the worker
                        VMs.
                      items:
                        properties:
                          label:
                            description: Label is the label of the Disk.
                            type: string
                          sizeGb:
                            description: SizeGb is the size in Gb of the disk.
                            format: int64
                            minimum: 1
                            type: integer
                        required:
                        - sizeGb
                        type: object
                      minItems: 1
                      type: array
                  required:
                  - datastore
                  - disks
                  type: object
              required:
              - masters
              - workers
              type: object
          required:
          - provider
          - compute
          - network
          - storage
          type: object
        status:
          properties:
            conditions:
              description: Represents the latest available observations of a VSphere
                Plan current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of VSphere Plan condition.
                    type: string
                required:
                - type
                - status
                - lastUpdateTime
                - lastTransitionTime
                - reason
                - message
                type: object
              type: array
            observedGeneration:
              description: The generation observed by the VSphere Plan controller.
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
