apiVersion: v1
kind: Secret
metadata:
  name: bosh-credentials
type: Opaque
data:
  url: "W1JFREFDVEVEXQo="
  clientId: "W1JFREFDVEVEXQo="
  clientSecret: "W1JFREFDVEVEXQo="
  CACert: "W1JFREFDVEVEXQo="
