apiVersion: pks.vcna.io/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: "dummy-cluster-sample"
spec:
  description: "This is a sample Dummy Cluster"
  externalHostname: "dummy-cluster-sample.example.com"
  provisioner:
    type: "DUMMY"
    credentialsSecretRef:
      name: "bosh-credentials"
      namespace: "default"
  planRef:
    kind: "VSpherePlan"
    name: "vsphereplan-sample"
    namespace: "default"
  kubernetesProfileRef:
    name: "kubernetesprofile-sample"
    namespace: "default"
