apiVersion: pks.vcna.io/v1alpha1
kind: KubernetesProfile
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: "kubernetesprofile-sample"
spec:
  description: "This is a sample Kubernetes Profile"
  versions:
    master: "1.13.0"
    worker: "1.13.0"
  network:
    serviceDomain: "cluster.local"
    servicesCIDRBlocks:
      - "10.96.0.0/12"
    podsCIDRBlock:
      - "192.168.0.0/16"
