// +build !ignore_autogenerated

/*
 * Copyright (c) 2019 VMware, Inc. All rights reserved.
 */
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSComputeMastersSpec) DeepCopyInto(out *AWSComputeMastersSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSComputeMastersSpec.
func (in *AWSComputeMastersSpec) DeepCopy() *AWSComputeMastersSpec {
	if in == nil {
		return nil
	}
	out := new(AWSComputeMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSComputeSpec) DeepCopyInto(out *AWSComputeSpec) {
	*out = *in
	in.MastersSpec.DeepCopyInto(&out.MastersSpec)
	in.WorkersSpec.DeepCopyInto(&out.WorkersSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSComputeSpec.
func (in *AWSComputeSpec) DeepCopy() *AWSComputeSpec {
	if in == nil {
		return nil
	}
	out := new(AWSComputeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSComputeWorkersSpec) DeepCopyInto(out *AWSComputeWorkersSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSComputeWorkersSpec.
func (in *AWSComputeWorkersSpec) DeepCopy() *AWSComputeWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(AWSComputeWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSDiskSpec) DeepCopyInto(out *AWSDiskSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSDiskSpec.
func (in *AWSDiskSpec) DeepCopy() *AWSDiskSpec {
	if in == nil {
		return nil
	}
	out := new(AWSDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSNetworkSpec) DeepCopyInto(out *AWSNetworkSpec) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSNetworkSpec.
func (in *AWSNetworkSpec) DeepCopy() *AWSNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(AWSNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPlan) DeepCopyInto(out *AWSPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPlan.
func (in *AWSPlan) DeepCopy() *AWSPlan {
	if in == nil {
		return nil
	}
	out := new(AWSPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPlanCondition) DeepCopyInto(out *AWSPlanCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPlanCondition.
func (in *AWSPlanCondition) DeepCopy() *AWSPlanCondition {
	if in == nil {
		return nil
	}
	out := new(AWSPlanCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPlanList) DeepCopyInto(out *AWSPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPlanList.
func (in *AWSPlanList) DeepCopy() *AWSPlanList {
	if in == nil {
		return nil
	}
	out := new(AWSPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPlanSpec) DeepCopyInto(out *AWSPlanSpec) {
	*out = *in
	out.ProviderSpec = in.ProviderSpec
	in.ComputeSpec.DeepCopyInto(&out.ComputeSpec)
	in.NetworkSpec.DeepCopyInto(&out.NetworkSpec)
	in.StorageSpec.DeepCopyInto(&out.StorageSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPlanSpec.
func (in *AWSPlanSpec) DeepCopy() *AWSPlanSpec {
	if in == nil {
		return nil
	}
	out := new(AWSPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPlanStatus) DeepCopyInto(out *AWSPlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AWSPlanCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPlanStatus.
func (in *AWSPlanStatus) DeepCopy() *AWSPlanStatus {
	if in == nil {
		return nil
	}
	out := new(AWSPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSProviderSpec) DeepCopyInto(out *AWSProviderSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSProviderSpec.
func (in *AWSProviderSpec) DeepCopy() *AWSProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AWSProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSStorageMastersSpec) DeepCopyInto(out *AWSStorageMastersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]AWSDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSStorageMastersSpec.
func (in *AWSStorageMastersSpec) DeepCopy() *AWSStorageMastersSpec {
	if in == nil {
		return nil
	}
	out := new(AWSStorageMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSStorageSpec) DeepCopyInto(out *AWSStorageSpec) {
	*out = *in
	in.MastersSpec.DeepCopyInto(&out.MastersSpec)
	in.WorkersSpec.DeepCopyInto(&out.WorkersSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSStorageSpec.
func (in *AWSStorageSpec) DeepCopy() *AWSStorageSpec {
	if in == nil {
		return nil
	}
	out := new(AWSStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSStorageWorkersSpec) DeepCopyInto(out *AWSStorageWorkersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]AWSDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSStorageWorkersSpec.
func (in *AWSStorageWorkersSpec) DeepCopy() *AWSStorageWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(AWSStorageWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureComputeMastersSpec) DeepCopyInto(out *AzureComputeMastersSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureComputeMastersSpec.
func (in *AzureComputeMastersSpec) DeepCopy() *AzureComputeMastersSpec {
	if in == nil {
		return nil
	}
	out := new(AzureComputeMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureComputeSpec) DeepCopyInto(out *AzureComputeSpec) {
	*out = *in
	out.MastersSpec = in.MastersSpec
	out.WorkersSpec = in.WorkersSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureComputeSpec.
func (in *AzureComputeSpec) DeepCopy() *AzureComputeSpec {
	if in == nil {
		return nil
	}
	out := new(AzureComputeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureComputeWorkersSpec) DeepCopyInto(out *AzureComputeWorkersSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureComputeWorkersSpec.
func (in *AzureComputeWorkersSpec) DeepCopy() *AzureComputeWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(AzureComputeWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDiskSpec) DeepCopyInto(out *AzureDiskSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDiskSpec.
func (in *AzureDiskSpec) DeepCopy() *AzureDiskSpec {
	if in == nil {
		return nil
	}
	out := new(AzureDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureNetworkSpec) DeepCopyInto(out *AzureNetworkSpec) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureNetworkSpec.
func (in *AzureNetworkSpec) DeepCopy() *AzureNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(AzureNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePlan) DeepCopyInto(out *AzurePlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePlan.
func (in *AzurePlan) DeepCopy() *AzurePlan {
	if in == nil {
		return nil
	}
	out := new(AzurePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePlanCondition) DeepCopyInto(out *AzurePlanCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePlanCondition.
func (in *AzurePlanCondition) DeepCopy() *AzurePlanCondition {
	if in == nil {
		return nil
	}
	out := new(AzurePlanCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePlanList) DeepCopyInto(out *AzurePlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzurePlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePlanList.
func (in *AzurePlanList) DeepCopy() *AzurePlanList {
	if in == nil {
		return nil
	}
	out := new(AzurePlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePlanSpec) DeepCopyInto(out *AzurePlanSpec) {
	*out = *in
	out.ProviderSpec = in.ProviderSpec
	out.ComputeSpec = in.ComputeSpec
	in.NetworkSpec.DeepCopyInto(&out.NetworkSpec)
	in.StorageSpec.DeepCopyInto(&out.StorageSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePlanSpec.
func (in *AzurePlanSpec) DeepCopy() *AzurePlanSpec {
	if in == nil {
		return nil
	}
	out := new(AzurePlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePlanStatus) DeepCopyInto(out *AzurePlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AzurePlanCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePlanStatus.
func (in *AzurePlanStatus) DeepCopy() *AzurePlanStatus {
	if in == nil {
		return nil
	}
	out := new(AzurePlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureProviderSpec) DeepCopyInto(out *AzureProviderSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureProviderSpec.
func (in *AzureProviderSpec) DeepCopy() *AzureProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AzureProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorageMastersSpec) DeepCopyInto(out *AzureStorageMastersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]AzureDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorageMastersSpec.
func (in *AzureStorageMastersSpec) DeepCopy() *AzureStorageMastersSpec {
	if in == nil {
		return nil
	}
	out := new(AzureStorageMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorageSpec) DeepCopyInto(out *AzureStorageSpec) {
	*out = *in
	in.MastersSpec.DeepCopyInto(&out.MastersSpec)
	in.WorkersSpec.DeepCopyInto(&out.WorkersSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorageSpec.
func (in *AzureStorageSpec) DeepCopy() *AzureStorageSpec {
	if in == nil {
		return nil
	}
	out := new(AzureStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorageWorkersSpec) DeepCopyInto(out *AzureStorageWorkersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]AzureDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorageWorkersSpec.
func (in *AzureStorageWorkersSpec) DeepCopy() *AzureStorageWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(AzureStorageWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCondition) DeepCopyInto(out *ClusterCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCondition.
func (in *ClusterCondition) DeepCopy() *ClusterCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLastOperation) DeepCopyInto(out *ClusterLastOperation) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLastOperation.
func (in *ClusterLastOperation) DeepCopy() *ClusterLastOperation {
	if in == nil {
		return nil
	}
	out := new(ClusterLastOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	out.ProvisionerSpec = in.ProvisionerSpec
	out.PlanRef = in.PlanRef
	out.KubernetesProfileRef = in.KubernetesProfileRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.LastOperation != nil {
		in, out := &in.LastOperation, &out.LastOperation
		*out = new(ClusterLastOperation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ClusterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPComputeMastersSpec) DeepCopyInto(out *GCPComputeMastersSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPComputeMastersSpec.
func (in *GCPComputeMastersSpec) DeepCopy() *GCPComputeMastersSpec {
	if in == nil {
		return nil
	}
	out := new(GCPComputeMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPComputeSpec) DeepCopyInto(out *GCPComputeSpec) {
	*out = *in
	in.MastersSpec.DeepCopyInto(&out.MastersSpec)
	in.WorkersSpec.DeepCopyInto(&out.WorkersSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPComputeSpec.
func (in *GCPComputeSpec) DeepCopy() *GCPComputeSpec {
	if in == nil {
		return nil
	}
	out := new(GCPComputeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPComputeWorkersSpec) DeepCopyInto(out *GCPComputeWorkersSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPComputeWorkersSpec.
func (in *GCPComputeWorkersSpec) DeepCopy() *GCPComputeWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(GCPComputeWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPDiskSpec) DeepCopyInto(out *GCPDiskSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPDiskSpec.
func (in *GCPDiskSpec) DeepCopy() *GCPDiskSpec {
	if in == nil {
		return nil
	}
	out := new(GCPDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPNetworkSpec) DeepCopyInto(out *GCPNetworkSpec) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPNetworkSpec.
func (in *GCPNetworkSpec) DeepCopy() *GCPNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(GCPNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPlan) DeepCopyInto(out *GCPPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPlan.
func (in *GCPPlan) DeepCopy() *GCPPlan {
	if in == nil {
		return nil
	}
	out := new(GCPPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPlanCondition) DeepCopyInto(out *GCPPlanCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPlanCondition.
func (in *GCPPlanCondition) DeepCopy() *GCPPlanCondition {
	if in == nil {
		return nil
	}
	out := new(GCPPlanCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPlanList) DeepCopyInto(out *GCPPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPlanList.
func (in *GCPPlanList) DeepCopy() *GCPPlanList {
	if in == nil {
		return nil
	}
	out := new(GCPPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPlanSpec) DeepCopyInto(out *GCPPlanSpec) {
	*out = *in
	out.ProviderSpec = in.ProviderSpec
	in.ComputeSpec.DeepCopyInto(&out.ComputeSpec)
	in.NetworkSpec.DeepCopyInto(&out.NetworkSpec)
	in.StorageSpec.DeepCopyInto(&out.StorageSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPlanSpec.
func (in *GCPPlanSpec) DeepCopy() *GCPPlanSpec {
	if in == nil {
		return nil
	}
	out := new(GCPPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPlanStatus) DeepCopyInto(out *GCPPlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]GCPPlanCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPlanStatus.
func (in *GCPPlanStatus) DeepCopy() *GCPPlanStatus {
	if in == nil {
		return nil
	}
	out := new(GCPPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPProviderSpec) DeepCopyInto(out *GCPProviderSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPProviderSpec.
func (in *GCPProviderSpec) DeepCopy() *GCPProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GCPProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPStorageMastersSpec) DeepCopyInto(out *GCPStorageMastersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]GCPDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPStorageMastersSpec.
func (in *GCPStorageMastersSpec) DeepCopy() *GCPStorageMastersSpec {
	if in == nil {
		return nil
	}
	out := new(GCPStorageMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPStorageSpec) DeepCopyInto(out *GCPStorageSpec) {
	*out = *in
	in.MastersSpec.DeepCopyInto(&out.MastersSpec)
	in.WorkersSpec.DeepCopyInto(&out.WorkersSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPStorageSpec.
func (in *GCPStorageSpec) DeepCopy() *GCPStorageSpec {
	if in == nil {
		return nil
	}
	out := new(GCPStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPStorageWorkersSpec) DeepCopyInto(out *GCPStorageWorkersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]GCPDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPStorageWorkersSpec.
func (in *GCPStorageWorkersSpec) DeepCopy() *GCPStorageWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(GCPStorageWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesNetworkSpec) DeepCopyInto(out *KubernetesNetworkSpec) {
	*out = *in
	if in.ServicesCIDRBlocks != nil {
		in, out := &in.ServicesCIDRBlocks, &out.ServicesCIDRBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodsCIDRBlocks != nil {
		in, out := &in.PodsCIDRBlocks, &out.PodsCIDRBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesNetworkSpec.
func (in *KubernetesNetworkSpec) DeepCopy() *KubernetesNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesProfile) DeepCopyInto(out *KubernetesProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesProfile.
func (in *KubernetesProfile) DeepCopy() *KubernetesProfile {
	if in == nil {
		return nil
	}
	out := new(KubernetesProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesProfileCondition) DeepCopyInto(out *KubernetesProfileCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesProfileCondition.
func (in *KubernetesProfileCondition) DeepCopy() *KubernetesProfileCondition {
	if in == nil {
		return nil
	}
	out := new(KubernetesProfileCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesProfileList) DeepCopyInto(out *KubernetesProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubernetesProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesProfileList.
func (in *KubernetesProfileList) DeepCopy() *KubernetesProfileList {
	if in == nil {
		return nil
	}
	out := new(KubernetesProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesProfileSpec) DeepCopyInto(out *KubernetesProfileSpec) {
	*out = *in
	out.Versions = in.Versions
	in.NetworkSpec.DeepCopyInto(&out.NetworkSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesProfileSpec.
func (in *KubernetesProfileSpec) DeepCopy() *KubernetesProfileSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesProfileStatus) DeepCopyInto(out *KubernetesProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]KubernetesProfileCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesProfileStatus.
func (in *KubernetesProfileStatus) DeepCopy() *KubernetesProfileStatus {
	if in == nil {
		return nil
	}
	out := new(KubernetesProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesVersionsSpec) DeepCopyInto(out *KubernetesVersionsSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesVersionsSpec.
func (in *KubernetesVersionsSpec) DeepCopy() *KubernetesVersionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesVersionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ODBPlan) DeepCopyInto(out *ODBPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ODBPlan.
func (in *ODBPlan) DeepCopy() *ODBPlan {
	if in == nil {
		return nil
	}
	out := new(ODBPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ODBPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ODBPlanCondition) DeepCopyInto(out *ODBPlanCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ODBPlanCondition.
func (in *ODBPlanCondition) DeepCopy() *ODBPlanCondition {
	if in == nil {
		return nil
	}
	out := new(ODBPlanCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ODBPlanList) DeepCopyInto(out *ODBPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ODBPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ODBPlanList.
func (in *ODBPlanList) DeepCopy() *ODBPlanList {
	if in == nil {
		return nil
	}
	out := new(ODBPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ODBPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ODBPlanSpec) DeepCopyInto(out *ODBPlanSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ODBPlanSpec.
func (in *ODBPlanSpec) DeepCopy() *ODBPlanSpec {
	if in == nil {
		return nil
	}
	out := new(ODBPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ODBPlanStatus) DeepCopyInto(out *ODBPlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ODBPlanCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ODBPlanStatus.
func (in *ODBPlanStatus) DeepCopy() *ODBPlanStatus {
	if in == nil {
		return nil
	}
	out := new(ODBPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerSpec) DeepCopyInto(out *ProvisionerSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerSpec.
func (in *ProvisionerSpec) DeepCopy() *ProvisionerSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisionerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereComputeMastersSpec) DeepCopyInto(out *VSphereComputeMastersSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]VSphereZoneSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereComputeMastersSpec.
func (in *VSphereComputeMastersSpec) DeepCopy() *VSphereComputeMastersSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereComputeMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereComputeSpec) DeepCopyInto(out *VSphereComputeSpec) {
	*out = *in
	in.MastersSpec.DeepCopyInto(&out.MastersSpec)
	in.WorkersSpec.DeepCopyInto(&out.WorkersSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereComputeSpec.
func (in *VSphereComputeSpec) DeepCopy() *VSphereComputeSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereComputeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereComputeWorkersSpec) DeepCopyInto(out *VSphereComputeWorkersSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]VSphereZoneSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereComputeWorkersSpec.
func (in *VSphereComputeWorkersSpec) DeepCopy() *VSphereComputeWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereComputeWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereDVSNetworkSpec) DeepCopyInto(out *VSphereDVSNetworkSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereDVSNetworkSpec.
func (in *VSphereDVSNetworkSpec) DeepCopy() *VSphereDVSNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereDVSNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereDiskSpec) DeepCopyInto(out *VSphereDiskSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereDiskSpec.
func (in *VSphereDiskSpec) DeepCopy() *VSphereDiskSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereNSXTNetworkSpec) DeepCopyInto(out *VSphereNSXTNetworkSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.IPBlockIDs != nil {
		in, out := &in.IPBlockIDs, &out.IPBlockIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FloatingIPPoolIDs != nil {
		in, out := &in.FloatingIPPoolIDs, &out.FloatingIPPoolIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereNSXTNetworkSpec.
func (in *VSphereNSXTNetworkSpec) DeepCopy() *VSphereNSXTNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereNSXTNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereNetworkSpec) DeepCopyInto(out *VSphereNetworkSpec) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DVSNetworkSpec != nil {
		in, out := &in.DVSNetworkSpec, &out.DVSNetworkSpec
		*out = new(VSphereDVSNetworkSpec)
		**out = **in
	}
	if in.NSXTNetworkSpec != nil {
		in, out := &in.NSXTNetworkSpec, &out.NSXTNetworkSpec
		*out = new(VSphereNSXTNetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereNetworkSpec.
func (in *VSphereNetworkSpec) DeepCopy() *VSphereNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSpherePlan) DeepCopyInto(out *VSpherePlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSpherePlan.
func (in *VSpherePlan) DeepCopy() *VSpherePlan {
	if in == nil {
		return nil
	}
	out := new(VSpherePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSpherePlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSpherePlanCondition) DeepCopyInto(out *VSpherePlanCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSpherePlanCondition.
func (in *VSpherePlanCondition) DeepCopy() *VSpherePlanCondition {
	if in == nil {
		return nil
	}
	out := new(VSpherePlanCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSpherePlanList) DeepCopyInto(out *VSpherePlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSpherePlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSpherePlanList.
func (in *VSpherePlanList) DeepCopy() *VSpherePlanList {
	if in == nil {
		return nil
	}
	out := new(VSpherePlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSpherePlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSpherePlanSpec) DeepCopyInto(out *VSpherePlanSpec) {
	*out = *in
	out.ProviderSpec = in.ProviderSpec
	in.ComputeSpec.DeepCopyInto(&out.ComputeSpec)
	in.NetworkSpec.DeepCopyInto(&out.NetworkSpec)
	in.StorageSpec.DeepCopyInto(&out.StorageSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSpherePlanSpec.
func (in *VSpherePlanSpec) DeepCopy() *VSpherePlanSpec {
	if in == nil {
		return nil
	}
	out := new(VSpherePlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSpherePlanStatus) DeepCopyInto(out *VSpherePlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]VSpherePlanCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSpherePlanStatus.
func (in *VSpherePlanStatus) DeepCopy() *VSpherePlanStatus {
	if in == nil {
		return nil
	}
	out := new(VSpherePlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereProviderSpec) DeepCopyInto(out *VSphereProviderSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereProviderSpec.
func (in *VSphereProviderSpec) DeepCopy() *VSphereProviderSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereStorageMastersSpec) DeepCopyInto(out *VSphereStorageMastersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]VSphereDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereStorageMastersSpec.
func (in *VSphereStorageMastersSpec) DeepCopy() *VSphereStorageMastersSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereStorageMastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereStorageSpec) DeepCopyInto(out *VSphereStorageSpec) {
	*out = *in
	in.MastersSpec.DeepCopyInto(&out.MastersSpec)
	in.WorkersSpec.DeepCopyInto(&out.WorkersSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereStorageSpec.
func (in *VSphereStorageSpec) DeepCopy() *VSphereStorageSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereStorageWorkersSpec) DeepCopyInto(out *VSphereStorageWorkersSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]VSphereDiskSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereStorageWorkersSpec.
func (in *VSphereStorageWorkersSpec) DeepCopy() *VSphereStorageWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereStorageWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereZoneSpec) DeepCopyInto(out *VSphereZoneSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereZoneSpec.
func (in *VSphereZoneSpec) DeepCopy() *VSphereZoneSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereZoneSpec)
	in.DeepCopyInto(out)
	return out
}
